apiVersion: pipelines.kubeflow.org/v2beta1
kind: PipelineVersion
metadata:
  resourceVersion: '52075987'
  name: sleep-demo
  uid: 15d306ed-c065-4a2c-9c13-eb11a9bfadaa
  creationTimestamp: '2026-09-01T00:25:39Z'
  generation: 1
  managedFields:
    - apiVersion: pipelines.kubeflow.org/v2beta1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            .: {}
            'f:pipelines.kubeflow.org/pipeline-id': {}
          'f:ownerReferences':
            .: {}
            'k:{"uid":"8dcdebbe-e180-4f0d-b29d-dc4996ed13fb"}': {}
        'f:spec':
          .: {}
          'f:displayName': {}
          'f:pipelineName': {}
          'f:pipelineSpec':
            .: {}
            'f:components':
              .: {}
              'f:comp-data-prep':
                .: {}
                'f:executorLabel': {}
              'f:comp-evaluate-model':
                .: {}
                'f:executorLabel': {}
              'f:comp-register-model':
                .: {}
                'f:executorLabel': {}
              'f:comp-train-model':
                .: {}
                'f:executorLabel': {}
            'f:deploymentSpec':
              .: {}
              'f:executors':
                .: {}
                'f:exec-data-prep':
                  .: {}
                  'f:container':
                    .: {}
                    'f:args': {}
                    'f:command': {}
                    'f:image': {}
                'f:exec-evaluate-model':
                  .: {}
                  'f:container':
                    .: {}
                    'f:args': {}
                    'f:command': {}
                    'f:image': {}
                'f:exec-register-model':
                  .: {}
                  'f:container':
                    .: {}
                    'f:args': {}
                    'f:command': {}
                    'f:image': {}
                'f:exec-train-model':
                  .: {}
                  'f:container':
                    .: {}
                    'f:args': {}
                    'f:command': {}
                    'f:image': {}
            'f:pipelineInfo':
              .: {}
              'f:description': {}
              'f:name': {}
            'f:root':
              .: {}
              'f:dag':
                .: {}
                'f:tasks':
                  .: {}
                  'f:data-prep':
                    .: {}
                    'f:cachingOptions': {}
                    'f:componentRef':
                      .: {}
                      'f:name': {}
                    'f:taskInfo':
                      .: {}
                      'f:name': {}
                  'f:evaluate-model':
                    .: {}
                    'f:cachingOptions': {}
                    'f:componentRef':
                      .: {}
                      'f:name': {}
                    'f:dependentTasks': {}
                    'f:taskInfo':
                      .: {}
                      'f:name': {}
                  'f:register-model':
                    .: {}
                    'f:cachingOptions': {}
                    'f:componentRef':
                      .: {}
                      'f:name': {}
                    'f:dependentTasks': {}
                    'f:taskInfo':
                      .: {}
                      'f:name': {}
                  'f:train-model':
                    .: {}
                    'f:cachingOptions': {}
                    'f:componentRef':
                      .: {}
                      'f:name': {}
                    'f:dependentTasks': {}
                    'f:taskInfo':
                      .: {}
                      'f:name': {}
            'f:schemaVersion': {}
            'f:sdkVersion': {}
      manager: apiserver
      operation: Update
      time: '2026-09-01T00:25:38Z'
    - apiVersion: pipelines.kubeflow.org/v2beta1
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          .: {}
          'f:conditions': {}
      manager: apiserver
      operation: Update
      subresource: status
      time: '2026-09-01T00:25:39Z'
  namespace: pipeline-demo
  ownerReferences:
    - apiVersion: pipelines.kubeflow.org/v2beta1
      blockOwnerDeletion: true
      kind: Pipeline
      name: sleep-demo
      uid: 8dcdebbe-e180-4f0d-b29d-dc4996ed13fb
  labels:
    pipelines.kubeflow.org/pipeline: sleep-demo
    pipelines.kubeflow.org/pipeline-id: 8dcdebbe-e180-4f0d-b29d-dc4996ed13fb
spec:
  displayName: sleep-demo
  pipelineName: sleep-demo
  pipelineSpec:
    components:
      comp-data-prep:
        executorLabel: exec-data-prep
      comp-evaluate-model:
        executorLabel: exec-evaluate-model
      comp-register-model:
        executorLabel: exec-register-model
      comp-train-model:
        executorLabel: exec-train-model
    deploymentSpec:
      executors:
        exec-data-prep:
          container:
            args:
              - sleep 10
            command:
              - sh
              - '-c'
            image: 'registry.redhat.io/ubi9/ubi-minimal:latest'
        exec-evaluate-model:
          container:
            args:
              - sleep 10
            command:
              - sh
              - '-c'
            image: 'registry.redhat.io/ubi9/ubi-minimal:latest'
        exec-register-model:
          container:
            args:
              - sleep 10
            command:
              - sh
              - '-c'
            image: 'registry.redhat.io/ubi9/ubi-minimal:latest'
        exec-train-model:
          container:
            args:
              - sleep 10
            command:
              - sh
              - '-c'
            image: 'registry.redhat.io/ubi9/ubi-minimal:latest'
    pipelineInfo:
      description: Simple four-step pipeline template
      name: sleep-pipeline-template
    root:
      dag:
        tasks:
          data-prep:
            cachingOptions: {}
            componentRef:
              name: comp-data-prep
            taskInfo:
              name: data-prep
          evaluate-model:
            cachingOptions: {}
            componentRef:
              name: comp-evaluate-model
            dependentTasks:
              - train-model
            taskInfo:
              name: evaluate-model
          register-model:
            cachingOptions: {}
            componentRef:
              name: comp-register-model
            dependentTasks:
              - train-model
            taskInfo:
              name: register-model
          train-model:
            cachingOptions: {}
            componentRef:
              name: comp-train-model
            dependentTasks:
              - data-prep
            taskInfo:
              name: train-model
    schemaVersion: 2.1.0
    sdkVersion: kfp-2.14.4
status:
  conditions:
    - message: READY
      reason: READY
      status: 'True'
      type: PipelineVersionStatus
