apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pipeline-demo

resources:
  - run.yaml

configMapGenerator:
  - name: parameters
    literals:
      - JOB_NAME=remote-pipeline-run-002

replacements:
  # Set the Job name
  - source:
      kind: ConfigMap
      name: parameters
      fieldPath: data.JOB_NAME
    targets:
      - select:
          kind: Job
          name: JOB_NAME_PLACEHOLDER
        fieldPaths:
          - metadata.name
  # Set the Run display name
  - source:
      kind: ConfigMap
      name: parameters
      fieldPath: data.JOB_NAME
    targets:
      - select:
          kind: Job
          name: JOB_NAME_PLACEHOLDER
        fieldPaths:
          # Note that the path selecter is to the name, not the value we want to replace. 
          - spec.template.spec.containers.[name=trigger-run].env.[name=RUN_DISPLAY_NAME].value
